version: 2
updates:
  # 1.7.x
  - package-ecosystem: maven
    target-branch: 1.7.x
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependency-upgrade

  # main
  - package-ecosystem: maven
    target-branch: main
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependency-upgrade
