name: CI Build

on:
  pull_request:
  push:
    branches:
      - main
      - '*.x'

jobs:
  build:
    if: github.repository == 'evgeniycheban/spring-data-reindexer'
    uses: ./.github/workflows/build.yml
  build-aot:
    if: github.repository == 'evgeniycheban/spring-data-reindexer'
    uses: ./.github/workflows/build-aot.yml
  build-aot-query-format-v2:
    if: github.repository == 'evgeniycheban/spring-data-reindexer'
    uses: ./.github/workflows/build-aot-query-format-v2.yml
