name: Release Build

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'minor-dev'
        type: choice
        options:
          - major-dev
          - minor-dev
          - patch-dev
          - major-rel
          - minor-rel

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'evgeniycheban/spring-data-reindexer'
    env:
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Prepare release
        run: |
          case "${{ inputs.release_type }}" in
             major-dev) RELEASE_POLICY=SemVerMajorDevelopment ;;
             minor-dev) RELEASE_POLICY=SemVerMinorDevelopment ;;
             patch-dev) RELEASE_POLICY=SemVerPatchDevelopment ;;
             major-rel) RELEASE_POLICY=SemVerMajorRelease ;;
             minor-rel) RELEASE_POLICY=SemVerMinorRelease ;;
             *) echo "Invalid release_type: ${{ inputs.release_type }}" >&2; exit 1 ;;
          esac
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          ./mvnw --batch-mode release:prepare -Pci,pre-release -DprojectVersionPolicyId=$RELEASE_POLICY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: sonatype-nexus-staging
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Perform release
        run: |
          ./mvnw --batch-mode release:perform -Pci,release
          curl --request POST \
               --user "${{ secrets.MAVEN_USERNAME }}:${{ secrets.MAVEN_PASSWORD }}" \
               --url "https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/io.github.evgeniycheban"
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
